language: node_js
node_js:
  - "4.1.2"
before_install:
  - npm install -g npm
  - npm --version
  - npm install -g bower
  - npm install -g gulp
  - npm install -g mocha
addons:
  mariadb: "10.1"
before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS newapi_testing;" -uroot
  - mysql -e "CREATE DATABASE IF NOT EXISTS newapi_development;" -uroot
  - mysql -e "CREATE USER 'newapi'@'localhost' IDENTIFIED BY 'newapi';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON newapi_testing.* to 'newapi'@'localhost';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON newapi_development.* to 'newapi'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
  - NODE_ENV=testing ./node_modules/.bin/sequelize db:migrate
  - NODE_ENV=development ./node_modules/.bin/sequelize db:migrate
  - NODE_ENV=testing ./node_modules/.bin/sequelize db:seed
  - NODE_ENV=development ./node_modules/.bin/sequelize db:seed
  - mkdir logs
env:
  - MOCHA_SUITES=all PROJECT_ROOT=$PWD NODE_ENV=testing
script: mocha -r mocha-steps test/e2e/suiteRunner.js && mocha test/unit/**/**.spec.js
